version: 2
jobs:
  deploy-gate:
    docker:
      - image: ubuntu:17.10
    steps:
      - run:
          name: Deploy gate is a failed job
          command: exit 1

  deploy-job:
    docker:
      - image: ubuntu:17.10
    steps:
      - run:
          name: Deploy job
          command: echo "This should not be running"

workflows:
  version: 2
  test:
    jobs:
      - deploy-gate:
          filters:
            branches:
              only:
                - master
                - staging
                - production
      - deploy-job:
          requires:
            - deploy-gate
